name: example-workflow
on:
  push:
      branches:
      - main
  pull_request:
      branches:
      - main
jobs:
  production-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # install our fork as the main repo is archived
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/holy-evening-chillers/sqf.git@master

      # one step for each folder to lint
      - name: Lint init files
        run: |
          sqflint init*.sqf
